spring.application.name=producto
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=dalushop;encrypt=false;trustServerCertificate=false
spring.datasource.username=sa
spring.datasource.password=admin#123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect